<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\TopicContent;
use App\Models\TopicContentTranslation;
use App\Jobs\GenerateMultilanguageAudioJob;
use Illuminate\Support\Facades\Log;
use Throwable;

class GenerateMissingTopicAudio extends Command
{
    protected $signature = 'audio:generate-missing
                            {--sync : Generate immediately instead of queue}
                            {--limit= : Limit number of records}
                            {--retry=3 : Number of job retries}';

    protected $description =
        'Generate only missing Hindi and Punjabi audio for existing topic contents';

    public function handle(): int
    {
        $this->info('==========================================');
        $this->info('Starting missing Hindi/Punjabi audio generation...');
        $this->info('==========================================');

        $sync = (bool) $this->option('sync');

        $limit = $this->option('limit')
            ? (int) $this->option('limit')
            : null;

        $generatedCount = 0;
        $skippedCount = 0;
        $failedCount = 0;

        /*
        |--------------------------------------------------------------------------
        | Get Existing Topic Contents
        |--------------------------------------------------------------------------
        |
        | English audio is not generated by this command.
        |
        */

        $contentQuery = TopicContent::query()
            ->where('status', 1)
            ->where('publish_status', 'published')
            ->whereNull('deleted_at')
            ->where('type', 'text')
            ->whereNotNull('content')
            ->whereRaw("TRIM(content) != ''")
            ->orderBy('id', 'asc');

        if ($limit !== null) {
            $contentQuery->limit($limit);
        }

        $contents = $contentQuery->get();

        $this->info(
            "Existing topic contents found: {$contents->count()}"
        );

        foreach ($contents as $content) {

            foreach (['hi', 'pa'] as $languageCode) {

                try {

                    /*
                    |--------------------------------------------------------------------------
                    | Find Existing Translation
                    |--------------------------------------------------------------------------
                    */

                    $translation = TopicContentTranslation::query()
                        ->where('topic_content_id', $content->id)
                        ->where('language_code', $languageCode)
                        ->first();

                    /*
                    |--------------------------------------------------------------------------
                    | Create Translation Row If Missing
                    |--------------------------------------------------------------------------
                    */

                    if (!$translation) {

                        $translation = TopicContentTranslation::create([
                            'topic_content_id' => $content->id,
                            'language_code' => $languageCode,
                            'title' => null,
                            'content' => null,
                        ]);

                        $this->line(
                            "Created {$languageCode} translation row for Content ID {$content->id}"
                        );
                    }

                    /*
                    |--------------------------------------------------------------------------
                    | Skip Existing Audio
                    |--------------------------------------------------------------------------
                    */

                    if (
                        !empty($translation->audio_path) &&
                        !empty($translation->audio_generated_at)
                    ) {

                        $skippedCount++;

                        $this->line(
                            "Skipped {$languageCode} Content ID {$content->id}: Audio already exists"
                        );

                        Log::channel('ai')->info(
                            'COMMAND MULTILANGUAGE AUDIO SKIPPED',
                            [
                                'content_id' => $content->id,
                                'translation_id' => $translation->id,
                                'language' => $languageCode,
                                'audio_path' => $translation->audio_path,
                                'audio_generated_at' => $translation->audio_generated_at,
                            ]
                        );

                        continue;
                    }

                    /*
                    |--------------------------------------------------------------------------
                    | Dispatch Only Missing Audio
                    |--------------------------------------------------------------------------
                    */

                    $this->line(
                        "Generating missing {$languageCode} audio for Content ID {$content->id}"
                    );

                    if ($sync) {

                        GenerateMultilanguageAudioJob::dispatchSync(
                            $content->id,
                            $languageCode,
                            $translation->id,
                            false
                        );

                        $this->info(
                            "Generated {$languageCode} audio: Content ID {$content->id}"
                        );

                    } else {

                        GenerateMultilanguageAudioJob::dispatch(
                            $content->id,
                            $languageCode,
                            $translation->id,
                            false
                        );

                        $this->info(
                            "Queued {$languageCode} audio: Content ID {$content->id}"
                        );
                    }

                    $generatedCount++;

                } catch (Throwable $e) {

                    $failedCount++;

                    Log::channel('ai')->error(
                        'COMMAND MULTILANGUAGE AUDIO FAILED',
                        [
                            'content_id' => $content->id,
                            'language' => $languageCode,
                            'error' => $e->getMessage(),
                        ]
                    );

                    $this->error(
                        "Failed {$languageCode} Content ID {$content->id}: {$e->getMessage()}"
                    );

                    continue;
                }
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Summary
        |--------------------------------------------------------------------------
        */

        $this->newLine();

        $this->info('==========================================');
        $this->info('Missing Audio Generation Summary');
        $this->info('==========================================');

        $this->info(
            "Hindi/Punjabi jobs dispatched: {$generatedCount}"
        );

        $this->warn(
            "Already existing audio skipped: {$skippedCount}"
        );

        $this->error(
            "Failed jobs: {$failedCount}"
        );

        if (!$sync) {

            $this->newLine();

            $this->warn('Jobs have been sent to the queue.');

            $this->line(
                'php artisan queue:work --tries=3 --timeout=600'
            );
        }

        $this->newLine();

        $this->info(
            'Missing Hindi/Punjabi audio generation completed.'
        );

        return self::SUCCESS;
    }
}
