<?php

namespace App\Modules\Admin\Import\Services\Support;

class HtmlNodeHelper
{
    /*
    |--------------------------------------------------------------------------
    | Get Clean Text
    |--------------------------------------------------------------------------
    */

    public function getText(string $html): string
    {
        $text = html_entity_decode(
            strip_tags($html),
            ENT_QUOTES | ENT_HTML5,
            'UTF-8'
        );

        $text = preg_replace('/\s+/u', ' ', $text);

        /*
        |--------------------------------------------------------------------------
        | Remove Word Bullets
        |--------------------------------------------------------------------------
        */

        $text = preg_replace(
            '/^[●•▪◦◆►]+\s*/u',
            '',
            $text
        );

        return trim($text);
    }

    /*
    |--------------------------------------------------------------------------
    | Module Detection
    |--------------------------------------------------------------------------
    */

    public function isModule(string $text): bool
    {
        return preg_match(
            '/^Module\s+(No\.?\s*)?\d+(\s*:)?/i',
            trim($text)
        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Chapter Detection
    |--------------------------------------------------------------------------
    */

    public function isChapter(string $text): bool
    {
        return preg_match(
            '/^Chapter\s+\d+(\.\d+)?(\s*:)?/i',
            trim($text)
        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Topic Detection
    |--------------------------------------------------------------------------
    */

    public function isTopic(string $text): bool
    {
        return preg_match(
            '/^Topic\s+\d+(\.\d+){0,2}(\s*:)?/i',
            trim($text)
        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Header / Footer Detection
    |--------------------------------------------------------------------------
    */

    public function isHeaderFooter(string $text): bool
    {
        $text = trim($text);

        if ($text === '') {
            return false;
        }

        return

            /*
            |--------------------------------------------------------------
            | Page Numbers
            */

            preg_match('/^Page\s+\d+/i', $text)

            ||

            preg_match('/^\d+\s*$/', $text)

            ||

            /*
            |--------------------------------------------------------------
            | Running Header
            */

            preg_match('/Level\s+\d+\s*\|\s*Module\s+\d+/i', $text)

            ||

            preg_match('/Chapter\s+\d+\s*\|\s*Topic\s+\d+/i', $text)

            ||

            /*
            |--------------------------------------------------------------
            | Copyright
            */

            preg_match('/copyright/i', $text)

            ||

            preg_match('/all rights reserved/i', $text)

            ||

            /*
            |--------------------------------------------------------------
            | Confidential
            */

            preg_match('/confidential/i', $text)

            ||

            /*
            |--------------------------------------------------------------
            | Generated
            */

            preg_match('/generated by/i', $text)

            ||

            preg_match('/printed on/i', $text);
    }

    /*
    |--------------------------------------------------------------------------
    | Assessment Heading
    |--------------------------------------------------------------------------
    */

    public function isAssessmentHeading(string $text): bool
    {
        return preg_match(

            '/^(Assessment|Topic Assessment|Quiz|MCQs?|Knowledge Check|Review Questions)$/i',

            trim($text)

        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Question Detection
    |--------------------------------------------------------------------------
    */

    public function isQuestion(string $text): bool
    {
        return preg_match(

            '/^(Q\s*\d+|Question\s*\d+|\d+\.)/i',

            trim($text)

        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Option Detection
    |--------------------------------------------------------------------------
    */

    public function isOption(string $text): bool
    {
        return preg_match(

            '/^(A|B|C|D)[\.\)]/i',

            trim($text)

        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Answer Detection
    |--------------------------------------------------------------------------
    */

    public function isAnswer(string $text): bool
    {
        return preg_match(

            '/^(Correct\s*Answer|Answer)\s*:/i',

            trim($text)

        ) === 1;
    }

    /*
    |--------------------------------------------------------------------------
    | Remove Legacy Identifiers
    |--------------------------------------------------------------------------
    |
    | Old payloads may still contain:
    |
    | 1.1.1.H1
    | 1.1.1.C1
    | 1.1.1.D
    | 1.1.1.Q1
    |
    | They are OPTIONAL in V3.
    | Remove only if present.
    |--------------------------------------------------------------------------
    */

    public function stripIdentifiers(string $text): string
    {
        return trim(

            preg_replace(

                '/^\d+(\.\d+){0,2}\.(H\d+|C\d+|D|Q\d+)\s*/i',

                '',

                trim($text)

            )

        );
    }
}